### ISSUE TITLE
Invalid instruction exception comes before cartridge interrupt when removing cartridge

### ISSUE THREAD

**Issue by lxylxy123456** [UCDClassNitta/riscv-console#14]
It seems that when the simulator is running in cartridge's instructions, and then the user presses REM, the machine will first receive an invalid instruction exception (mcause = 0x00000002), and then it will receive the cartridge interrupt for cartridge removed (mcause = 0x8000000b,  interrupt pending = 0x1, cartridge status = 0x0)

I think the expected behaviour should be cartridge interrupt first, then invalid instruction exception. (actually my OS will move user's PC to somewhere else, so there will be no invalid instruction exception). 

To reproduce, see https://github.com/lxylxy123456/riscv-console/blob/bug7/riscv-bug7/README.md
The code is in repo `git@github.com:lxylxy123456/riscv-console`, branch `bug7`
After running the experiment, you should see something like this:
![图片](https://user-images.githubusercontent.com/9337403/107135591-d4e14d00-68b0-11eb-9886-8810cd34d320.png)

**Comment by cjnitta** [comment]
I could understand that being desirable, but in a real system the external interrupt may not make it to the CPU for determination before the invalid instruction has already been fetched. Also if interrupts are disabled during the execution, there wouldn't be the possibility to guarantee that. I'll see if there is clean way to force the evaluation of the interrupts during the removal.

**Comment by lxylxy123456** [comment]
In Piazza @68, you also mentioned that the invalid instruction exception may be used to indicate cartridge removal.
So I am implementing my invalid instruction exception this way:
* If `mepc` is in the 0x20000000 memory region, and cartridge status is 0 (not inserted), then call the cartridge removal interrupt instead.
* Else, raise a kernel panic

However, now I found a situation:
* If the user first load a big cartridge, with a main loop in 0x200aaaaa - 0x200aaabb
* Then the user does not press REM, but press INS directly and load a small cartridge (valid instruction only < 0x20000ccc)
* Then there will be a invalid instruction exception before the cartridge interrupt, but the `mepc` is 0x200aaaab, but cartridge status is 1 (because the smaller cartridge is already inserted).

I think the ideal solution is to be able to force cartridge interrupt. As an alternative, INS should be blocked when cartridge is already inserted

**Comment by cjnitta** [comment]
I was thinking about the re-INS issue as well. Maybe instead of doing INS and INS again with a forced REM in between. I could change back to a cartridge button that is a toggle. If a valid cartridge is inserted, the user has to hit to remove the cartridge before inserting the valid one.

**Comment by lxylxy123456** [comment]
As mentioned in today's lecture, it is possible for the user to use the debug mode to remove a cartridge and insert a new one immediately:

https://user-images.githubusercontent.com/9337403/107448837-4dd1e600-6af7-11eb-863d-21ba4d8fedb8.mp4

**Comment by cjnitta** [comment]
This is no different than the user hitting command twice, or hitting the button and releasing while it is stopped. In debug where the system is stopped unrealistic changes can occur.
