### ISSUE TITLE
Problem with small sprite in the latter half?

### ISSUE THREAD

**Issue by lxylxy123456** [UCDClassNitta/riscv-console#18]
To reproduce, patch the repo with the following (using git-apply), or use the following repo. Then run riscv-example

Web: https://github.com/lxylxy123456/riscv-console/tree/bug16/riscv-example
Repo: git@github.com:lxylxy123456/riscv-console.git
Branch: bug16
Folder: riscv-example

```
diff --git a/riscv-example/src/main.c b/riscv-example/src/main.c
index 2d1a12c..bfcc7d7 100644
--- a/riscv-example/src/main.c
+++ b/riscv-example/src/main.c
@@ -24,6 +24,22 @@ int main() {
     VIDEO_MEMORY[11] = '!';
     VIDEO_MEMORY[12] = 'X';
 
+	// Mode
+	*(uint32_t*) 0x500FF414 = 0x1;
+
+	// Palette
+	* (volatile uint32_t *) 0x500fd000 = 0xffffffff;
+
+	// Control
+	int max = 128;
+	int i = 90;
+	while (1)
+		for (int i = 0; i < max; i++) {
+			int ii = (i + max - 1) % max;
+			* (volatile uint32_t *) (0x500ff214 + 4 * i) = 0x7fe42108;
+			* (volatile uint32_t *) (0x500ff214 + 4 * ii) = 0x7fe42109;
+			for (int i = 0; i < 0x10000; i++);
+		}
 
     while (1) {
         int c = a + b + global;
```

Each time the code makes a white square with small sprite `i` on the screen, and then remove the square of small sprite `i - 1`. So the small sprite should always appear on the screen. However, actually the square flashes periodically. 
If we change `int max = 128;` to `int max = 64;`, the problem disappears. So I think there is some problem with around small sprite >= 70 (see image below, where I am trying to draw 3 lines of small sprites).

![图片](https://user-images.githubusercontent.com/9337403/109470729-acb6bb00-7a24-11eb-9733-d1688ddd4e8a.png)

**Comment by cjnitta** [comment]
The code you posted has everything in the same location, but you are showing sprites spread out in the image. I assume there is different code for that? In terms of the flashing part of the issue might be that the updates aren't synchronized to the video interrupt. Have you tried using fewer, but further in the series? Is it a matter of the total sprites on screen?

**Comment by lxylxy123456** [comment]
The image I posted is from another code. 
I think the flashing is not due to video synchronization. Because the flashing is slow and I have used `for (int i = 0; i < 0x10000; i++);` to "sleep" for some time. 
I will try the things later. I guess it is likely to be related to the total sprites on the screen.

**Comment by lxylxy123456** [comment]
I think the problem is related to total number of sprites. See the video below.
Basically when iterating from 0 to 128, some sprites of higher number do not show. However, iterating from 0 to 64 or from 64 to 128 do not have this problem.

Web: https://github.com/lxylxy123456/riscv-console/tree/bug16b/riscv-example
Repo: git@github.com:lxylxy123456/riscv-console.git
Branch: bug16b
Folder: riscv-example

Diff from `main`:
```
diff --git a/riscv-example/src/main.c b/riscv-example/src/main.c
index 2d1a12c..564230a 100644
--- a/riscv-example/src/main.c
+++ b/riscv-example/src/main.c
@@ -24,6 +24,32 @@ int main() {
     VIDEO_MEMORY[11] = '!';
     VIDEO_MEMORY[12] = 'X';
 
+	// Mode
+	*(uint32_t*) 0x500FF414 = 0x1;
+
+	// Palette
+	* (volatile uint32_t *) 0x500fd000 = 0xffffffff;
+
+	// Control
+	int ii = -1;
+	int i = 90;
+	while (1)
+		for (int i = 0; i < 128; i++) {
+			{
+				int x = 16 + i % 16 * 16;
+				int y = 16 + i / 16 * 16;
+				* (volatile uint32_t *) (0x500ff214 + 4 * i) =
+					0x7fe00000 | (y << 12) | (x << 2);
+			}
+			if (ii != -1) {
+				int x = 16 + ii % 16 * 16;
+				int y = 16 + ii / 16 * 16;
+				* (volatile uint32_t *) (0x500ff214 + 4 * ii) =
+					0x7fe00001 | (y << 12) | (x << 2);
+			}
+			for (int i = 0; i < 0x10000; i++);
+			ii = i;
+		}
 
     while (1) {
         int c = a + b + global;
```

https://user-images.githubusercontent.com/9337403/109563230-57b28d80-7a94-11eb-9cd1-0eaf9c77b357.mp4

**Comment by cjnitta** [comment]
Have you tried a combination of large and small sprites? Maybe 64 large and 64 small, etc? If it is an issue of number of sprites, I may just need to rework some of the code in the video controller that works with the resource contexts.

**Comment by cjnitta** [comment]
Are you setting things once, or are you updating continually? If you are updating continually, you may want to wait until the video interrupt then do the updates.

**Comment by lxylxy123456** [comment]
See updated comment above.
In this test I am doing everything at once. 
I have waited for a long time before taking the screen shot, so I think I can ignore the video interrupt. Do you mean that if there is a write during video interrupt, undefined behavior will happen? I think the image may be seamed, but it should be fixed at the next video interrupt.

**Comment by cjnitta** [comment]
I could see there being strange behavior if writing during the video refresh. If you only do the change once, then you just need to wait until the video refresh after, which should happen immediately in terms of how fast you would take a screenshot. How many small sprites are supposed to be on the screen in your lower screenshot?

**Comment by lxylxy123456** [comment]
It should be 3 lines, each line should be 28 sprites. So 84 in total.

**Comment by lxylxy123456** [comment]
FYI Here is the relevant part of my video memory (It will be good to support printing these info on the terminal in the future, to avoid copying and pasting):
![图片](https://user-images.githubusercontent.com/9337403/109581928-0e713680-7ab2-11eb-913d-6a0008c82e58.png)
![图片](https://user-images.githubusercontent.com/9337403/109582238-a40cc600-7ab2-11eb-83c8-48e1588a55cd.png)

**Comment by lxylxy123456** [comment]
In `bug16b` above, adding `* (volatile uint32_t *) 0x500FD400 = 0xff0000ff;` will make it more visible. Still, it looks to be a problem of total number of small sprites
![图片](https://user-images.githubusercontent.com/9337403/109583443-c4d61b00-7ab4-11eb-8e08-92eec3f7857b.png)
![图片](https://user-images.githubusercontent.com/9337403/109583451-c869a200-7ab4-11eb-9e3b-a5e7b3848594.png)
![图片](https://user-images.githubusercontent.com/9337403/109583527-e3d4ad00-7ab4-11eb-8966-74eeedbb7a84.png)

**Comment by cjnitta** [comment]
It seems like going beyond 69 small sprites is a problem. Not sure why that would be the limit. I'm trying to figure it out.

**Comment by cjnitta** [comment]
Think I found the bug. Try and pull the most current.

**Comment by lxylxy123456** [comment]
Looks good to me. Thanks for fixing the bug.
