### ISSUE TITLE
Enable C++ STL in riscv-example

### ISSUE THREAD

**Issue by XiaoxingChen** [UCDClassNitta/riscv-console#24]
Hi Professor, 
I am trying to enable C++ features in `riscv-example` thus the development could be easier. Currently the project can be compiled with `riscv32-unknown-elf-g++` and the ELF works correctly on the simulator. However if I introduce C++ STL containers like `std::vector` or `std::map`, the simulator freezed after I click the `PWR` button.

After some debugging I can figure out that `malloc()` and `free()` functions work correctly but the code will freeze if I explicitly call `new` and `delete` operator.
Here is what I did to the code:

1. Modify linker script `riscv-example/riscv32-console.ld` to support heap operation.
2. Wrap interrupt handler with `extern "C" {}`.
3. Add `libc`, `libstdc++`, `libgcc` as target link libraries. Add `-fno-exceptions` as CFLAGS. 

`malloc()` and `free()` work at this step. If I only use `class` or `std::array`, the `riscv-example` still works. But if I introduce other STL container with dynamic memory, the simulator will freeze.

4. Overloading `new`, `new[]`, `delete`, `delete[]`. Then `std::map` works but `std::vector` still doesn't work.

Here is the [branch](https://github.com/UCDClassNitta/riscv-console/compare/main...XiaoxingChen:riscv-console:chenxx/new_delete_issue) that I made the modification. 

Could you please kindly give me some suggestions to debug the problem? Thank you!

**Comment by cjnitta** [comment]
Support for standard library requires system calls. You need to implement sbrk in order for malloc to work in the newlib implementation. See https://sourceware.org/newlib/libc.html#index-sbrk for hints.

**Comment by XiaoxingChen** [comment]
Hi Professor, 
I forgot to mention I have added `-lnosys` as target link library. `sbrk` is within it. Here is the link 
 https://github.com/eblot/newlib/blob/master/libgloss/libnosys/sbrk.c

I have tested that `malloc()` and `free()` works. It's the `new` and `delete` operators that don't work.

Thank you.

**Comment by cjnitta** [comment]
Did you add support for the ctors and dtors in the pre-main code?

**Comment by XiaoxingChen** [comment]
Could you please kindly give more details about that, or some reference links? I declared STL containers in `main()` function. I just write it in same way as what I do on x86 machine. The constructors of a `std::vector` for example, is supposed to be called after its declaration right? Because the compiler has been changed to `riscv32-unknown-elf-g++` in Makefile.

**Comment by cjnitta** [comment]
There is a lot more that needs to be supported for C++. new/delete may not actually be calling malloc/free in the implementation of the STL. What you need is to do is make sure all of the required structures are initialized before entering main. This means you will need to do the work in the init. One source that might be helpful is https://alex-robenko.gitbook.io/bare_metal_cpp/ Support C++ is much more complicated than supporting only C.
