### ISSUE TITLE
Bug in resetting memory after firmware is changed

### ISSUE THREAD

**Issue by lxylxy123456** [UCDClassNitta/riscv-console#5]
I think the memory is not cleared correctly when the firmware is changed.
To reproduce
1. Replace `riscv-example/src/main.c` with the code at the end, and build
2. Start a simulator
3. Bring firmware with the riscv-example's executable
4. Press PWR
5. Press "x" and "d" a few times (to move the "X" on the screen off its current x and y position)
6. Bring firmware with the riscv-example's executable (again)
7. Now the "X" should come back to the original position
8. Press "d"
9. Now "X" jumps to a different position and stars moving from there (undesired behavior)
```
#include <stdint.h>

volatile int global = 42;
volatile uint32_t controller_status = 0;

volatile char *VIDEO_MEMORY = (volatile char *)(0x50000000 + 0xFE800);
void refresh() {
    static int x_pos = 12, y_pos = 0;
    if(controller_status){
        VIDEO_MEMORY[x_pos + y_pos * 0x40] = ' ';
        if(controller_status & 0x1){
            x_pos--;
        }
        if(controller_status & 0x2){
            y_pos--;
        }
        if(controller_status & 0x4){
            y_pos++;
        }
        if(controller_status & 0x8){
            x_pos++;
        }
        VIDEO_MEMORY[x_pos + y_pos * 0x40] = 'X';
    }
}

int main() {
    int a = 4;
    int b = 12;
    int last_global = 42;
    int x_pos = 12;

    VIDEO_MEMORY[0] = 'H';
    VIDEO_MEMORY[1] = 'e';
    VIDEO_MEMORY[2] = 'l';
    VIDEO_MEMORY[3] = 'l';
    VIDEO_MEMORY[4] = 'o';
    VIDEO_MEMORY[5] = ' ';
    VIDEO_MEMORY[6] = 'W';
    VIDEO_MEMORY[7] = 'o';
    VIDEO_MEMORY[8] = 'r';
    VIDEO_MEMORY[9] = 'l';
    VIDEO_MEMORY[10] = 'd';
    VIDEO_MEMORY[11] = '!';
    VIDEO_MEMORY[12] = 'X';


    while (1) {
        int c = a + b + global;
        if(global != last_global){
        	refresh();
            last_global = global;
        }
    }
    return 0;
}
```

**Comment by lxylxy123456** [comment]
https://user-images.githubusercontent.com/9337403/105116207-20a59100-5a7f-11eb-9127-78bc665760bb.mp4

**Comment by lxylxy123456** [comment]
I believe the cause is that `x_pos = 12, y_pos = 0` are defined as static variables. Since `y_pos` is zero, it is not initialized when the program is loaded (the loader assumes the memory is 0). However, since the memory is not cleared after the firmware re-load, the `y_pos` is effectively not initialized to 0.

**Comment by cjnitta** [comment]
The issue is actually most likely an issue of bss not being zeroed out. I think the init is missing this. From _bss to _ebss should be zeroed out. See if that fixes the problem.

**Comment by lxylxy123456** [comment]
I am wondering, is it the OS's job to clear the memory in a machine? Or can it assume that memory is cleared by hardware?

**Comment by lxylxy123456** [comment]
I am able to solve the problem by letting the firmware zero out `.bss`:
Add the following to global definitions in `startup.c`:
```
extern uint8_t _bss;
extern uint8_t _ebss;
```
Add the following to `void init(void)`:
```
	Base = &_bss;
	while (Base < &_ebss)
		*Base++ = 0;
```

**Comment by cjnitta** [comment]
Zeroing out the .bss is the responsibility of the C application, so the firmware needs to do it for itself. The zeroing out for the app is up to the design of the OS. Is there startup code the OS handles, or is it in each app?

**Comment by lxylxy123456** [comment]
I think I understand. So basically the firmware (i.e. the OS) needs to zero out the memory it needs for the `.bss` section. 
For the app's `.bss` section, it depends on the OS's implementation (to decide whether the OS or the app clears the `.bss` section).

**Comment by cjnitta** [comment]
Yeah, basically it is a matter of how the information is stored in the cartridge. In order to do this, the information would need to be placed in a specific location in memory.
